/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardColumn: typeof import('./src/components/BoardColumn.vue')['default']
    DragDrop: typeof import('./src/components/DragDrop.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskModal: typeof import('./src/components/TaskModal.vue')['default']
  }
}
